[package]
name = "fast"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
aya.workspace = true
blazesym = "0.2.6"
bytemuck.workspace = true
clap.workspace = true
ctrlc.workspace = true
fast-common.workspace = true
humantime.workspace = true
libc.workspace = true

[build-dependencies]
aya-build.workspace = true
