[package]
name = "fast"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
aya.workspace = true
blazesym = "0.2.6"
bytemuck.workspace = true
clap.workspace = true
ctrlc.workspace = true
fast-common = { workspace = true, features = ["aya"] }
humantime.workspace = true
libc.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[build-dependencies]
aya-build.workspace = true
